baseURL = 'https://example.org/'
languageCode = 'zh-cn'

#ä»…å½“æ‚¨å°†ä¸»é¢˜ä¿ç•™åœ¨`themes`ç›®å½•ä¸­æ—¶æ‰æ·»åŠ å®ƒã€‚
#å¦‚æœæ‚¨ä½¿ç”¨ä¸»é¢˜ä½œä¸ºè¿œç¨‹Hugoæ¨¡å—ï¼Œè¯·åˆ é™¤å®ƒã€‚
theme = "terminal"
pagination.pagerSize = 5

#éœ€è¦è‰²åº¦å’Œè‡ªå®šä¹‰è¯­æ³•é«˜äº®æ˜¾ç¤ºã€‚
[markup.highlight]
  noClasses = false

[params]
#ä½ çš„ä¸»è¦å†…å®¹çš„ç›®å½•åï¼ˆé»˜è®¤ä¸º`content/posts`ï¼‰ã€‚
#è®¾ç½®å†…å®¹çš„åˆ—è¡¨å°†æ˜¾ç¤ºåœ¨æ‚¨çš„ç´¢å¼•é¡µé¢ï¼ˆbaseurlï¼‰ä¸Šã€‚
  contentTypeName = "posts"

#å¦‚æœå°†æ­¤è®¾ç½®ä¸º0ï¼Œåˆ™åªæœ‰è§¦å‘å™¨å¯è§
  showMenuItems = 5

# show selectoråˆ‡æ¢è¯­è¨€
  showLanguageSelector = false

#å°†ä¸»é¢˜è®¾ç½®ä¸ºå…¨å±å®½åº¦
  fullWidthTheme = false

# å…·æœ‰é»˜è®¤å®½åº¦çš„å±…ä¸­ä¸»é¢˜
  centerTheme = true
#å¦‚æœæ‚¨çš„èµ„æºç›®å½•åŒ…å«ä¸€ä¸ªåä¸º'cover'çš„å›¾åƒã€‚(jpg|Webpï¼‰â€²ï¼Œ|webp)`,
#åˆ™è¯¥æ–‡ä»¶å°†è¢«è‡ªåŠ¨ç”¨ä½œå°é¢ã€‚
#æœ‰äº†è¿™ä¸ªé€‰é¡¹ï¼Œä½ å°±ä¸å¿…æŠŠ'cover'å‚æ•°æ”¾åœ¨ä¸€ä¸ªfront-matterä¸­ã€‚
  autoCover = true
#è®¾ç½®postä»¥æ˜¾ç¤ºæœ€åæ›´æ–°
#å¦‚æœä½ ä½¿ç”¨gitï¼Œä½ å¯ä»¥å°†`enableGitInfo`è®¾ç½®ä¸º`true`ï¼Œç„¶åpostä¼šè‡ªåŠ¨è·å–æœ€åä¸€æ¬¡æ›´æ–°
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  # Set date/time format for posts
  # This will impact the date/time displayed on
  # index.html, the posts list page, and on posts themselves
  # This value can also be configured per-post on front matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  # dateFormat = "2006-01-02"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "ä¸­æ–‡"
    title = "æ–°åº·éš†å•†åŸ"

    [languages.en.params]
      subtitle = "ç»å•†ä¿¡ä¸ºæœ¬ï¼Œè¯šæ‹›å¤©ä¸‹å®¢ï¼›ç»è¥åˆ›æ–°ï¼ŒæœåŠ¡åˆ›æ–°"
      owner = "æ–°åº·éš†å•†åŸ"
      keywords = ""
      copyright = "æœ¬ç½‘ç«™ä¸ä»£è¡¨å®˜æ–¹ï¼Œä»…åšå…è´¹å±•ç¤º"
      menuMore = "æ›´å¤š"
      readMore = "é˜…è¯»å…¨æ–‡"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "é¡µé¢æœªæ‰¾åˆ°"
      missingBackButtonLabel = "è¿”å›é¦–é¡µ"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "æ–°åº·éš†å•†åŸ"
        logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "â¤ï¸å…³äºæˆ‘ä»¬"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "â˜ï¸æ‹›å•†ä¼åˆ’"
        url = "/contact"
      [[languages.en.menu.main]]
        identifier = "floors"
        name = "ğŸ¬æ¥¼å±‚æŒ‡å¼•"
        url = "/floors"
      [[languages.en.menu.main]]
        identifier = "hours"
        name = "ğŸ•—è¥ä¸šæ—¶é—´"
        url = "/hours"


[module]
  # In case you would like to make changes to the theme and keep it locally in you repository,
  # uncomment the line below (and correct the local path if necessary).
  # --
  # replacements = "github.com/panr/hugo-theme-terminal/v4 -> themes/terminal"
